ensure commands that release process requires are available

diff --git a/elektrum-release b/elektrum-release
--- a/elektrum-release
+++ b/elektrum-release
@@ -174,6 +174,8 @@ function check_branch() {
     log "Successfully checked current branch: ${current_branch}"
 }
 
+command -v git >/dev/null 2>&1 || { echo >&2 "Command 'git' not installed. Install using `brew install git`.  Aborting."; exit 1; }
+
 if [ "${1}" == '--help' ];
 then
     usage $0
